routes/web.php
<?php

use App\Http\Controllers\DaftarMatkul;
use App\Http\Controllers\Dashboard;
use App\Http\Controllers\DosenMatkul;
use App\Http\Controllers\Home;

Route::get('/', Home::class)->name('home');
Route::get('/dashboard', Dashboard::class)->name('dashboard')->middleware('auth');

Route::resource('daftar-matkul', DaftarMatkul::class);
Route::resource('dosen-matkul', DosenMatkul::class);

resources/views/daftar_kuliah/create.blade.php
@extends('laravolt::layouts.app')

@section('content')

<x-backlink url="{{ route('daftar-matkul.index') }}"></x-backlink>

<x-panel title="Tambah">
    {!! form()->post(route('daftar-matkul.store'))->horizontal()->multipart() !!}
    {!! form()->dropdown('mahasiswa_id',$mahasiswa)->placeholder('Pilih Nama Mahasiswa')->label('Nama Mahasiswa') !!}
    {!! form()->selectMultiple('matakuliah_id[]',$matkul)->placeholder('Masukkan Nama Mata Kuliah')->label('Nama Mata
    Kuliah')!!}
    {!! form()->action([
    form()->submit('Simpan Data matkul'),
    form()->link('Batal', route('daftar-matkul.index'))
    ]) !!}
    {!! form()->close() !!}
</x-panel>

@stop

resources/views/daftar_kuliah/edit.blade.php
@extends('laravolt::layouts.app')

@section('content')

<x-backlink url="{{ route('daftar-matkul.index') }}"></x-backlink>

<x-panel title="Edit Daftar Kuliah">
    {!! form()->bind($data)->put(route('daftar-matkul.update',$data->id))->horizontal()->multipart() !!}
    {!! form()->text('nama')->readonly()->label('Nama Mahasiswa') !!}
    {!! form()->selectMultiple('matakuliah_id[]',$matkul,$matkuls)->placeholder('Masukkan Mata
    Kuliah')->label('Nama Mata
    Kuliah')!!}
    {!! form()->action([
    form()->submit('Simpan'),
    form()->link('Batal', route('daftar-matkul.index'))
    ]) !!}
    {!! form()->close() !!}
</x-panel>

@stop

resources/views/daftar_kuliah/index.blade.php
@extends('laravolt::layouts.app')

@section('content')


<x-titlebar title="Daftar Kuliah">
    <x-item>
        <x-link label="Tambah " icon="plus" url="{{ route('daftar-matkul.create') }}"></x-link>
    </x-item>
</x-titlebar>

{!! Suitable::source($data)
->columns([
['header'=> 'No', 'field'=> 'id'],
['header' => 'Nama Mahasiswa', 'field' => 'nama'],
['header' => 'Mata Kuliah', 'raw' => function ($item){
$matkuls = array();
foreach ($item->matakuliah as $daf_kuliah) {
$matkuls[] = $daf_kuliah;
}
foreach ($matkuls as $item) {
echo "<li>$item->nama_matkul ($item->jum_sks sks)</li>";
}

}],
['header' => 'Total SKS', 'raw' => function ($item){
$totalSks = 0;
foreach ($item->matakuliah as $sks) {
$totalSks+= (int)$sks->jum_sks;
}
return $totalSks;
}],
['header'=>'Aksi','raw'=> function ($item){
return "<a href=".route('daftar-matkul.edit',$item->id)."><i class='edit icon'></i></a>";
}],
])
->render() !!}
@stop