routes/web.php
<?php

use App\Http\Controllers\DaftarMatkul;
use App\Http\Controllers\Dashboard;
use App\Http\Controllers\DosenMatkul;
use App\Http\Controllers\Home;

Route::get('/', Home::class)->name('home');
Route::get('/dashboard', Dashboard::class)->name('dashboard')->middleware('auth');

Route::resource('daftar-matkul', DaftarMatkul::class);
Route::resource('dosen-matkul', DosenMatkul::class);

app/Http/Controllers/DosenMatkul.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Modules\Dosen\Models\Dosen;
use Modules\Matakuliah\Models\Matakuliah;

class DosenMatkul extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $data = Dosen::with('matakuliah')->get();


        return view('dosen-matkul.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $dosen = Dosen::all()->pluck('nama', 'id');
        $matkul = Matakuliah::all()->pluck('nama_matkul', 'id');

        return view('dosen-matkul.create', compact('dosen', 'matkul'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        $dosen = Dosen::find($request->dosen_id);

        $matkul = $request->matakuliah_id;

        $dosen->matakuliah()->attach($matkul);
        return redirect()->back()->withSuccess(count($matkul) . ' Mata Kuliah berhasil diambil');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $data = Dosen::find($id);

        $matkul = Matakuliah::all()->pluck('nama_matkul', 'id');

        $pivot = DB::table('mahasiswa_matakuliah')->where('mahasiswa_id', $id)->get();

        $daf_matkul = array();
        foreach ($pivot as $item) {
            $id_matkul = MataKuliah::where('id', $item->matakuliah_id)->first();
            array_push($daf_matkul, $id_matkul->nama_matkul);
        }
        // dd($matkuls);

        return view('dosen-matkul.edit', compact('data', 'matkul', 'daf_matkul'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $matkul_tambahan_string = array();
        $matkul_lama_string =  array();
        $matkul_lama = array();

        //request dari form
        $request_matkul = $request->matakuliah_id;

        //memisahkan matkul
        foreach ($request_matkul as $item) {
            (int)$item;
            if ($item != 0) {
                array_push($matkul_tambahan_string, (int)$item);
            } else {
                array_push($matkul_lama_string, $item);
            }
        }

        //dapetikan id dari string matkul
        foreach ($matkul_lama_string as $item) {
            $matkul_str = MataKuliah::where('nama_matkul', $item)->select('id')->first();
            array_push($matkul_lama, $matkul_str->id);
        }

        //merge matkul lama dan terbaru
        $matkul_update = array_merge($matkul_tambahan_string, $matkul_lama);
        // dd($matkul_update);
        // dd($matkul_update);
        // simpan ke user
        $dosen = Dosen::find($id);

        $dosen->matakuliah()->sync($matkul_update);
        return redirect()->back()->withSuccess('Mata Kuliah berhasil di update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/dosen-matkul/create.blade.php
@extends('laravolt::layouts.app')

@section('content')

<x-backlink url="{{ route('dosen-matkul.index') }}"></x-backlink>

<x-panel title="Tambah">
    {!! form()->post(route('dosen-matkul.store'))->horizontal()->multipart() !!}
    {!! form()->dropdown('dosen_id',$dosen)->placeholder('Pilih Nama Dosen')->label('Nama Dosen') !!}
    {!! form()->selectMultiple('matakuliah_id[]',$matkul)->placeholder('Pilih Mata Kuliah')->label('Nama Mata
    Kuliah')!!}
    {!! form()->action([
    form()->submit('Simpan Data'),
    form()->link('Batal', route('dosen-matkul.index'))
    ]) !!}
    {!! form()->close() !!}
</x-panel>

@stop

resources/views/dosen-matkul/edit.blade.php
@extends('laravolt::layouts.app')

@section('content')

<x-backlink url="{{ route('dosen-matkul.index') }}"></x-backlink>

<x-panel title="Edit Daftar Kuliah">
    {!! form()->bind($data)->put(route('dosen-matkul.update',$data->id))->horizontal()->multipart() !!}
    {!! form()->text('nama')->readonly()->label('Nama Dosen') !!}
    {!! form()->selectMultiple('matakuliah_id[]',$matkul,$daf_matkul)->placeholder('Masukkan Mata
    Kuliah')->label('Nama Mata
    Kuliah')!!}
    {!! form()->action([
    form()->submit('Simpan'),
    form()->link('Batal', route('dosen-matkul.index'))
    ]) !!}
    {!! form()->close() !!}
</x-panel>

@stop

resources/views/dosen-matkul/index.blade.php
@extends('laravolt::layouts.app')

@section('content')


<x-titlebar title="Dosen Mata Kuliah">
    <x-item>
        <x-link label="Tambah " icon="plus" url="{{ route('dosen-matkul.create') }}"></x-link>
    </x-item>
</x-titlebar>

{!! Suitable::source($data)
->columns([
['header'=> 'No', 'field'=> 'id'],
['header' => 'Nama Dosen', 'field' => 'nama'],
['header' => 'Mata Kuliah yang diambil', 'raw' => function ($item){
$matkuls = array();
foreach ($item->matakuliah as $daf_kuliah) {
$matkuls[] = $daf_kuliah;
}
foreach ($matkuls as $item) {
echo "<li>$item->nama_matkul ($item->jum_sks sks)</li>";
}
}],
['header' => 'Total SKS Yang DiAmpu', 'raw' => function ($item){
$totalSks = 0;
foreach ($item->matakuliah as $sks) {
$totalSks+= (int)$sks->jum_sks;
}
return $totalSks;
}],
['header'=>'Aksi','raw'=> function ($item){
return "<a href=".route('dosen-matkul.edit',$item->id)."><i class='edit icon'></i></a>";
}],
])
->render() !!}
@stop